name: Better Reminder Build
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch: # 允许手动触发

jobs:
  build:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
              - platform: 'macos-latest' # for Arm based macs (M1 and above).
                target: 'aarch64-apple-darwin'
                args: '--target aarch64-apple-darwin'
              - platform: 'macos-latest' # for Intel based macs.
                target: 'x86_64-apple-darwin'
                args: '--target x86_64-apple-darwin'
              - platform: 'ubuntu-24.04'
                target: 'x86_64-unknown-linux-gnu'
                args: ''
              - platform: 'windows-latest'
                target: 'x86_64-pc-windows-msvc'
              - platform: 'windows-latest'
                target: 'i686-pc-windows-msvc'
              - platform: 'windows-latest'
                target: 'aarch64-pc-windows-msvc'
                args: '--target aarch64-pc-windows-msvc'


    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install rust target
        run: rustup target add ${{ matrix.target }}

      # Rust 设置
      - name: Rust setup
        uses: dtolnay/rust-toolchain@stable

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'

      # Node.js 设置
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          cache: 'npm'

      # 安装依赖
      - name: Install frontend dependencies
        run: npm install

      # Windows 特定依赖
      - name: Install Windows dependencies
        if: matrix.platform == 'windows-latest'
        run: |
          vcpkg install openssl:x64-windows-static-md
          echo "OPENSSL_DIR=C:/vcpkg/installed/x64-windows-static-md" >> $env:GITHUB_ENV
          echo "VCPKG_ROOT=C:/vcpkg" >> $env:GITHUB_ENV

      # macOS 特定依赖
      - name: Install macOS dependencies
        if: matrix.platform == 'macos-latest'
        run: |
          brew install openssl
          
      # Ubuntu 特定依赖    
      - name: Install Ubuntu dependencies
        if: matrix.platform == 'ubuntu-24.04' 
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf


      # 构建应用
      - name: Build the app
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
        with:
          tagName: build-${{ github.run_number }}
          releaseName: "Better-Reminder Build ${{ github.run_number }}"
          releaseBody: "自动构建版本"
          releaseDraft: false
          prerelease: false

      - name: Upload!
        uses: softprops/action-gh-release@v1
        if: success()
        with:
          tag_name: Better_Reminder_Build-${{ github.run_number }}
          files: |
            ${{ steps.build.outputs.artifactPaths }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
