name: Build Executables
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch: # 允许手动触发

jobs:
  build:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, windows-latest]
        include:
          - platform: macos-latest
            output-name: better-reminder-macos.dmg
          - platform: windows-latest
            output-name: better-reminder-windows.msi

    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Rust 设置
      - name: Rust setup
        uses: dtolnay/rust-toolchain@stable

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'

      # Node.js 设置
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          cache: 'npm'

      # 安装依赖
      - name: Install frontend dependencies
        run: npm install

      # Windows 特定依赖
      - name: Install Windows dependencies
        if: matrix.platform == 'windows-latest'
        run: |
          vcpkg install openssl:x64-windows-static-md
          echo "OPENSSL_DIR=C:/vcpkg/installed/x64-windows-static-md" >> $env:GITHUB_ENV
          echo "VCPKG_ROOT=C:/vcpkg" >> $env:GITHUB_ENV

      # macOS 特定依赖
      - name: Install macOS dependencies
        if: matrix.platform == 'macos-latest'
        run: |
          brew install openssl

      # 构建应用
      - name: Build the app
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
        with:
          tagName: build-${{ github.run_number }}
          releaseName: "Better-Reminder Build ${{ github.run_number }}"
          releaseBody: "自动构建版本"
          releaseDraft: true
          prerelease: true

      # 上传构建产物
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: better-reminder-${{ matrix.platform }}
          path: |
            src-tauri/target/release/bundle/dmg/*.dmg
            src-tauri/target/release/bundle/msi/*.msi
            src-tauri/target/release/bundle/app/*
          retention-days: 5
